### ISSUE TITLE
Prevent devDependencies from being deployed

### ISSUE THREAD

**Issue by 454de6e** [maiertech/capture#50]
Zeit's new feature to inspect production deployments of functions allows downloading the deployed code. Inspecting the code reveals that by default Zeit now also installs `devDependencies`.  Set `NODE_ENV` to `production` in `now.json`.

**Comment by maiertech** [comment]
Looks like it is not necessary any longer to set `NODE_ENV=production` to prevent `devDependencies` from being bundled into lambda.

**Comment by maiertech** [comment]
The size of the deployed lambda is slightly smaller when `NODE_ENV-production` is set in `now.json`. Therefore, no changes.
